AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  9cloud2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 9cloud2/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::789613278086:role/lambda-crawler'
